"""
Bootstrap Database Ingestion Script
Populates PostgreSQL (using fast COPY) or SQLite with:
1. 79,365 frozen source sites
2. 79,365 Model A baseline predictions / decisions
3. 79,365 Model B precomputed states
4. 297,348 daily activity records (site_daily_activity.parquet)
5. 297,348 historical Model C event replay records (site_daily_inference)
6. 79,365 materialized latest Model C status records (site_model_c)
7. External facility evidence layers (GFMR, GEM, ICAR)
8. Model stack version metadata
9. Initial operational alerts generated by DecisionEngine
"""

import os
import sys
import json
import hashlib
import time
import logging
from pathlib import Path
from datetime import date, datetime, timezone
import argparse
import pandas as pd
import numpy as np

# Ensure project root is in sys.path
_repo_root = Path(__file__).resolve().parents[2]
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

from backend.app.db.session import engine, init_db, SessionLocal, DEFAULT_DATABASE_URL
from backend.app.db.models import (
    SourceSite,
    FirmsDetection,
    SiteDailyActivity,
    SiteModelA,
    SiteModelAHistory,
    SiteModelAFeatures,
    SiteReferenceLabel,
    SiteModelB,
    SiteModelC,
    SiteDailyInference,
    FacilityEvidence,
    EventEvidence,
    CandidateSource,
    CandidateSourceDetection,
    SiteModelBHistory,
    StackSnapshot,
    ImageryCache,
    IngestionRun,
    FirmsBackfillWindow,
    ModelVersion,
    Alert
)
from backend.app.engines.decision_engine import DecisionEngine
from backend.app.engines.model_a import ModelAEngine
from backend.app.services.feature_builder import ORDERED_FEATURES, FEATURE_VERSION
from backend.app.services.firms_ingestion import normalize_acq_time
from backend.app.services.stack_readiness import (
    REQUIRED_FILES, PROJECT_ROOT, _active_manifest_issue, _verify_declared_checksums,
)
from backend.app.services.feature_validation import validate_feature_builder_snapshot

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

IS_POSTGRES = DEFAULT_DATABASE_URL.startswith("postgresql")


def get_raw_psycopg_conn():
    """Returns a raw psycopg connection for fast COPY operations if PostgreSQL."""
    if not IS_POSTGRES:
        return None
    # Strip +psycopg dialect if present for direct psycopg connect
    conn_url = DEFAULT_DATABASE_URL.replace("postgresql+psycopg://", "postgresql://")
    import psycopg
    return psycopg.connect(conn_url, autocommit=False)


def clean_database():
    """Truncates all tables cleanly."""
    logger.info("Cleaning database tables...")
    if IS_POSTGRES:
        conn = get_raw_psycopg_conn()
        try:
            with conn.cursor() as cur:
                cur.execute("""
                    TRUNCATE TABLE 
                        alerts,
                        site_daily_inference,
                        site_model_c,
                        site_model_b,
                        site_model_a_history,
                        site_model_a_features,
                        site_model_a,
                        site_model_b_history,
                        site_daily_activity,
                        candidate_source_detections,
                        firms_detections,
                        candidate_sources,
                        source_sites,
                        site_reference_labels,
                        event_evidence,
                        facility_evidence,
                        imagery_cache,
                        ingestion_runs,
                        stack_snapshots,
                        firms_backfill_windows,
                        model_versions
                    CASCADE;
                """)
            conn.commit()
        finally:
            conn.close()
    else:
        db = SessionLocal()
        try:
            for model in [Alert, SiteDailyInference, SiteModelC, SiteModelBHistory, SiteModelB,
                          SiteModelAHistory, SiteModelAFeatures, SiteModelA,
                          SiteReferenceLabel, SiteDailyActivity, FirmsDetection,
                          CandidateSourceDetection, CandidateSource, EventEvidence,
                          FacilityEvidence, ImageryCache, IngestionRun, StackSnapshot,
                          FirmsBackfillWindow,
                          ModelVersion, SourceSite]:
                db.query(model).delete()
            db.commit()
        finally:
            db.close()
    logger.info("Tables truncated successfully.")


def bootstrap_source_sites(csv_path: str, limit: int = None):
    """Loads 79,365 physical source sites."""
    t0 = time.time()
    logger.info(f"Bootstrapping source sites from {csv_path}...")
    if not os.path.exists(csv_path):
        logger.warning(f"File not found: {csv_path}")
        return 0

    df = pd.read_csv(csv_path, low_memory=False)
    if limit:
        df = df.iloc[:limit]

    total = len(df)
    logger.info(f"Loaded CSV in {time.time()-t0:.2f}s ({total} rows). Preparing insert...")

    lc_cols = ["tree_fraction", "shrub_fraction", "grass_fraction", "crop_fraction",
               "built_fraction", "bare_fraction", "water_fraction", "wetland_fraction", "mangrove_fraction"]
    sp_cols = ["spatial_median_m", "spatial_p90_m", "spatial_std_m"]

    # Check which cols exist
    available_lc = [c for c in lc_cols if c in df.columns]
    available_sp = [c for c in sp_cols if c in df.columns]

    now_iso = datetime.now(timezone.utc).isoformat()

    if IS_POSTGRES:
        conn = get_raw_psycopg_conn()
        try:
            with conn.cursor() as cur:
                with cur.copy(
                    "COPY source_sites (site_id, latitude, longitude, status, land_cover, spatial_stats, created_at) FROM STDIN"
                ) as copy:
                    for idx in range(total):
                        sid = df["site_id"].iat[idx]
                        lat = float(df["latitude"].iat[idx])
                        lon = float(df["longitude"].iat[idx])

                        lc = {c: float(df[c].iat[idx]) for c in available_lc if pd.notna(df[c].iat[idx])} or None
                        sp = {c: float(df[c].iat[idx]) for c in available_sp if pd.notna(df[c].iat[idx])} or None

                        copy.write_row((
                            sid, lat, lon, "ACTIVE",
                            json.dumps(lc) if lc else None,
                            json.dumps(sp) if sp else None,
                            now_iso
                        ))
            conn.commit()
        finally:
            conn.close()
    else:
        db = SessionLocal()
        try:
            records = []
            for idx in range(total):
                sid = df["site_id"].iat[idx]
                lat = float(df["latitude"].iat[idx])
                lon = float(df["longitude"].iat[idx])
                lc = {c: float(df[c].iat[idx]) for c in available_lc if pd.notna(df[c].iat[idx])} or None
                sp = {c: float(df[c].iat[idx]) for c in available_sp if pd.notna(df[c].iat[idx])} or None
                records.append({
                    "site_id": sid, "latitude": lat, "longitude": lon, "status": "ACTIVE",
                    "land_cover": lc, "spatial_stats": sp, "created_at": datetime.now(timezone.utc)
                })
                if len(records) >= 5000:
                    db.bulk_insert_mappings(SourceSite, records)
                    db.commit()
                    records = []
            if records:
                db.bulk_insert_mappings(SourceSite, records)
                db.commit()
        finally:
            db.close()

    logger.info(f"Inserted {total} source sites in {time.time()-t0:.2f}s.")
    return total


def hydrate_source_static_features(feature_path: str, limit: int = None):
    """Attach the frozen WorldCover/spatial feature groups to source sites."""
    if not os.path.exists(feature_path):
        raise FileNotFoundError(f"Authoritative Model A feature snapshot is required: {feature_path}")
    df = pd.read_parquet(feature_path)
    required = ["site_id", *ORDERED_FEATURES[-12:]]
    missing = [column for column in required if column not in df.columns]
    if missing:
        raise ValueError(f"Static feature snapshot is missing columns: {missing}")
    if limit:
        df = df.iloc[:limit]
    db = SessionLocal()
    try:
        for idx, row in df.iterrows():
            site = db.query(SourceSite).filter_by(site_id=str(row["site_id"])).one_or_none()
            if site is None:
                raise ValueError(f"Feature snapshot references unknown site {row['site_id']}")
            site.spatial_stats = {
                name: float(row[name]) for name in ORDERED_FEATURES[-12:-9] if pd.notna(row[name])
            }
            site.land_cover = {
                name: float(row[name]) for name in ORDERED_FEATURES[-9:] if pd.notna(row[name])
            }
            site.feature_version = FEATURE_VERSION
            if idx and idx % 2000 == 0:
                db.commit()
        db.commit()
    finally:
        db.close()
    return len(df)


def bootstrap_assigned_detections(parquet_path: str, limit: int = None):
    """Load the authoritative frozen detection-to-site membership snapshot."""
    if not os.path.exists(parquet_path):
        raise FileNotFoundError(f"Assigned FIRMS detection snapshot is required: {parquet_path}")
    df = pd.read_parquet(parquet_path)
    required = [
        "detection_id", "site_id", "latitude", "longitude", "acq_date",
        "acq_time", "frp", "satellite", "source_sensor", "daynight", "version",
    ]
    missing = [column for column in required if column not in df.columns]
    if missing:
        raise ValueError(f"Assigned detection snapshot is missing columns: {missing}")
    if limit:
        df = df.iloc[:limit]

    mappings = []
    for _, row in df.iterrows():
        mappings.append({
            "detection_id": str(row["detection_id"]),
            "source_sensor": _optional_string(row.get("source_sensor")) or "VIIRS_NOAA20_NRT",
            "satellite": str(row["satellite"]),
            "instrument": _optional_string(row.get("instrument")) or "VIIRS",
            "latitude": float(row["latitude"]),
            "longitude": float(row["longitude"]),
            "acq_date": pd.to_datetime(row["acq_date"]).date(),
            "acq_time": normalize_acq_time(row["acq_time"]),
            "frp": float(row["frp"]),
            "bright_ti4": _optional_float(row.get("bright_ti4", row.get("brightness"))),
            "bright_ti5": _optional_float(row.get("bright_ti5", row.get("bright_t31"))),
            "scan": _optional_float(row.get("scan")),
            "track": _optional_float(row.get("track")),
            "confidence": _optional_string(row.get("confidence")),
            "daynight": str(row["daynight"]),
            "version": _optional_string(row.get("version")),
            "source_site_id": str(row["site_id"]),
            "resolution_status": "FROZEN_MEMBER",
            "is_ambiguous": bool(row.get("is_ambiguous", False)),
            "candidate_site_ids": None,
            "assignment_distance_m": _optional_float(row.get("assignment_distance_m")),
            "raw_payload": {"bootstrap_source": Path(parquet_path).name},
            "ingested_at": datetime.now(timezone.utc),
        })

    db = SessionLocal()
    try:
        for start in range(0, len(mappings), 5000):
            db.bulk_insert_mappings(FirmsDetection, mappings[start:start + 5000])
            db.commit()
        latest = df.assign(acq_date=pd.to_datetime(df["acq_date"])).groupby("site_id")["acq_date"].max()
        for site_id, latest_seen in latest.items():
            site = db.query(SourceSite).filter_by(site_id=str(site_id)).one_or_none()
            if site is None:
                raise ValueError(f"Assigned detection snapshot references unknown site {site_id}")
            site.latest_seen = latest_seen.date()
        db.commit()
    finally:
        db.close()
    return len(mappings)


def _optional_float(value):
    return None if value is None or pd.isna(value) else float(value)


def _optional_string(value):
    return None if value is None or pd.isna(value) else str(value)


def bootstrap_model_a(feature_path: str, limit: int = None):
    """Run real A-Core inference from the frozen exact feature snapshot."""
    t0 = time.time()
    if not os.path.exists(feature_path):
        raise FileNotFoundError(
            f"Authoritative Model A feature snapshot is required: {feature_path}"
        )
    df = pd.read_parquet(feature_path)
    required = ["site_id", *ORDERED_FEATURES]
    missing = [column for column in required if column not in df.columns]
    if missing:
        raise ValueError(f"Model A feature snapshot is missing columns: {missing}")
    if limit:
        df = df.iloc[:limit]

    engine_a = ModelAEngine()
    feature_frame = df[ORDERED_FEATURES]
    if list(feature_frame.columns) != engine_a.feature_names:
        raise ValueError("Feature snapshot order disagrees with the Model A artifact.")
    cutoff_column = "feature_as_of_detection_date"
    if cutoff_column not in df.columns:
        raise ValueError("Feature snapshot must include feature_as_of_detection_date.")

    db = SessionLocal()
    try:
        now = datetime.now(timezone.utc)
        for idx in range(len(df)):
            site_id = str(df["site_id"].iat[idx])
            cutoff = pd.to_datetime(df[cutoff_column].iat[idx]).date()
            result = engine_a.predict(feature_frame.iloc[[idx]])
            feature_values = {
                name: (None if pd.isna(feature_frame[name].iat[idx]) else float(feature_frame[name].iat[idx]))
                for name in ORDERED_FEATURES
            }
            db.add(SiteModelA(
                site_id=site_id,
                core_probability=float(result["core_probability"]),
                class_name=result["class"],
                decision=result["decision"],
                prithvi_status="NOT_TRIGGERED",
                model_version="2026-09-04-r1",
                feature_version=FEATURE_VERSION,
                feature_as_of_detection_date=cutoff,
                computed_at=now,
            ))
            db.add(SiteModelAFeatures(
                site_id=site_id,
                feature_as_of_detection_date=cutoff,
                feature_version=FEATURE_VERSION,
                ordered_features=feature_values,
                computed_at=now,
            ))
            db.add(SiteModelAHistory(
                inference_id=f"BOOTSTRAP_A_{site_id}",
                site_id=site_id,
                feature_as_of_detection_date=cutoff,
                core_probability=float(result["core_probability"]),
                class_name=result["class"],
                decision=result["decision"],
                prithvi_status="NOT_TRIGGERED",
                model_version="2026-09-04-r1",
                feature_version=FEATURE_VERSION,
                computed_at=now,
            ))
            if idx and idx % 2000 == 0:
                db.commit()
        db.commit()
    finally:
        db.close()
    logger.info("Inserted %d genuine Model A states in %.2fs.", len(df), time.time() - t0)
    return len(df)


def bootstrap_reference_labels(csv_path: str, limit: int = None):
    """Load frozen research truth without creating runtime probabilities."""
    df = pd.read_csv(csv_path, low_memory=False)
    if limit:
        df = df.iloc[:limit]
    db = SessionLocal()
    try:
        records = []
        for _, row in df.iterrows():
            records.append({
                "site_id": str(row["site_id"]),
                "reference_class": _optional_string(row.get("label_final")) or "UNKNOWN",
                "label_tier": _optional_string(row.get("label_tier")),
                "industrial_source": _optional_string(row.get("industrial_source")),
                "nonindustrial_source": _optional_string(row.get("nonindustrial_source")),
                "evidence_metadata": {
                    "industrial_affirmative": _clean_bool(row.get("industrial_affirmative", False)),
                    "nonindustrial_affirmative": _clean_bool(row.get("nonindustrial_affirmative", False)),
                },
                "frozen_reference_version": "2025-final",
            })
        db.bulk_insert_mappings(SiteReferenceLabel, records)
        db.commit()
    finally:
        db.close()
    return len(df)


def _clean_bool(value) -> bool:
    if value is None or pd.isna(value):
        return False
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "y"}
    return bool(value)


def bootstrap_model_b_states(csv_path: str, limit: int = None):
    """Loads 79,365 precomputed Model B states."""
    t0 = time.time()
    logger.info(f"Bootstrapping Model B states from {csv_path}...")
    if not os.path.exists(csv_path):
        return 0

    df = pd.read_csv(csv_path)
    if limit:
        df = df.iloc[:limit]

    total = len(df)
    now_iso = datetime.now(timezone.utc).isoformat()

    conf_col = "state_confidence" if "state_confidence" in df.columns else ("confidence" if "confidence" in df.columns else None)
    reason_col = "state_reason" if "state_reason" in df.columns else ("reason" if "reason" in df.columns else None)

    if IS_POSTGRES:
        conn = get_raw_psycopg_conn()
        try:
            with conn.cursor() as cur:
                with cur.copy(
                    "COPY site_model_b (site_id, state, confidence, reason, days_since_last, active_days_windows, model_version, computed_at) FROM STDIN"
                ) as copy:
                    for idx in range(total):
                        sid = df["site_id"].iat[idx]
                        state = df["model_b_state"].iat[idx]
                        conf = df[conf_col].iat[idx] if conf_col and pd.notna(df[conf_col].iat[idx]) else "HIGH"
                        reason = df[reason_col].iat[idx] if reason_col and pd.notna(df[reason_col].iat[idx]) else ""
                        dsl = int(df["days_since_last"].iat[idx]) if pd.notna(df["days_since_last"].iat[idx]) else None

                        windows = _model_b_windows(df, idx)

                        copy.write_row((sid, state, conf, reason, dsl, json.dumps(windows), "2026-09-04-r1", now_iso))
            conn.commit()
        finally:
            conn.close()
    else:
        db = SessionLocal()
        try:
            records = []
            for idx in range(total):
                sid = df["site_id"].iat[idx]
                state = df["model_b_state"].iat[idx]
                conf = df[conf_col].iat[idx] if conf_col and pd.notna(df[conf_col].iat[idx]) else "HIGH"
                reason = df[reason_col].iat[idx] if reason_col and pd.notna(df[reason_col].iat[idx]) else ""
                dsl = int(df["days_since_last"].iat[idx]) if pd.notna(df["days_since_last"].iat[idx]) else None
                windows = _model_b_windows(df, idx)
                records.append({
                    "site_id": sid, "state": state, "confidence": conf, "reason": reason,
                    "days_since_last": dsl, "active_days_windows": windows,
                    "model_version": "2026-09-04-r1", "computed_at": datetime.now(timezone.utc)
                })
                if len(records) >= 5000:
                    db.bulk_insert_mappings(SiteModelB, records)
                    db.commit()
                    records = []
            if records:
                db.bulk_insert_mappings(SiteModelB, records)
                db.commit()
        finally:
            db.close()

    history_db = SessionLocal()
    try:
        history_rows = []
        cutoff = date(2025, 12, 31)
        for idx in range(total):
            history_rows.append({
                "site_id": str(df["site_id"].iat[idx]),
                "as_of_date": cutoff,
                "state": str(df["model_b_state"].iat[idx]),
                "confidence": str(df[conf_col].iat[idx]) if conf_col and pd.notna(df[conf_col].iat[idx]) else "HIGH",
                "reason": str(df[reason_col].iat[idx]) if reason_col and pd.notna(df[reason_col].iat[idx]) else "",
                "days_since_last": int(df["days_since_last"].iat[idx]) if pd.notna(df["days_since_last"].iat[idx]) else None,
                "active_days_windows": _model_b_windows(df, idx),
                "model_version": "2026-09-04-r1",
                "computed_at": datetime.now(timezone.utc),
            })
            if len(history_rows) >= 5000:
                history_db.bulk_insert_mappings(SiteModelBHistory, history_rows)
                history_db.commit()
                history_rows = []
        if history_rows:
            history_db.bulk_insert_mappings(SiteModelBHistory, history_rows)
            history_db.commit()
    finally:
        history_db.close()

    logger.info(f"Inserted {total} Model B states and cutoff history rows in {time.time()-t0:.2f}s.")
    return total


def _model_b_windows(frame: pd.DataFrame, idx: int) -> dict:
    result = {}
    for window in (30, 90, 180, 365):
        column = f"active_days_{window}"
        value = frame[column].iat[idx] if column in frame.columns else 0
        result[str(window)] = int(value) if pd.notna(value) else 0
    return result


def bootstrap_daily_activity(parquet_path: str, limit: int = None):
    """Loads 297,348 daily activity records."""
    t0 = time.time()
    logger.info(f"Bootstrapping site daily activity from {parquet_path}...")
    if not os.path.exists(parquet_path):
        return 0

    df = pd.read_parquet(parquet_path)
    if limit:
        df = df.iloc[:limit]

    total = len(df)
    now_iso = datetime.now(timezone.utc).isoformat()
    dates_str = df["acq_date"].dt.strftime("%Y-%m-%d").tolist()

    if IS_POSTGRES:
        conn = get_raw_psycopg_conn()
        try:
            with conn.cursor() as cur:
                with cur.copy(
                    "COPY site_daily_activity (site_id, acq_date, detections, mean_frp, max_frp, updated_at) FROM STDIN"
                ) as copy:
                    for idx in range(total):
                        sid = df["site_id"].iat[idx]
                        dt = dates_str[idx]
                        det = int(df["detections"].iat[idx])
                        mean_frp = float(df["mean_frp"].iat[idx])
                        max_frp = float(df["max_frp"].iat[idx])
                        copy.write_row((sid, dt, det, mean_frp, max_frp, now_iso))
            conn.commit()
        finally:
            conn.close()
    else:
        db = SessionLocal()
        try:
            records = []
            for idx in range(total):
                records.append({
                    "site_id": df["site_id"].iat[idx],
                    "acq_date": df["acq_date"].iat[idx].date(),
                    "detections": int(df["detections"].iat[idx]),
                    "mean_frp": float(df["mean_frp"].iat[idx]),
                    "max_frp": float(df["max_frp"].iat[idx]),
                    "updated_at": datetime.now(timezone.utc)
                })
                if len(records) >= 5000:
                    db.bulk_insert_mappings(SiteDailyActivity, records)
                    db.commit()
                    records = []
            if records:
                db.bulk_insert_mappings(SiteDailyActivity, records)
                db.commit()
        finally:
            db.close()

    logger.info(f"Inserted {total} daily activity records in {time.time()-t0:.2f}s.")
    return total


def bootstrap_model_c_and_inferences(parquet_path: str, limit: int = None):
    """
    Loads:
    1. site_daily_inference (all 297,348 rows from MODEL_C_EVENT_REPLAY_V3.parquet)
    2. site_model_c (materialized latest Model C status for all 79,365 sites)
    """
    t0 = time.time()
    logger.info(f"Bootstrapping Model C inferences & materialized state from {parquet_path}...")
    if not os.path.exists(parquet_path):
        return 0, 0

    df = pd.read_parquet(parquet_path)
    if limit:
        df = df.iloc[:limit]

    total_inferences = len(df)
    now_iso = datetime.now(timezone.utc).isoformat()
    dates_str = df["acq_date"].dt.strftime("%Y-%m-%d").tolist()

    # 1. Insert site_daily_inference
    logger.info(f"Inserting {total_inferences} daily inferences...")
    if IS_POSTGRES:
        conn = get_raw_psycopg_conn()
        try:
            with conn.cursor() as cur:
                with cur.copy(
                    "COPY site_daily_inference (site_id, acq_date, model_c_status, c_score, c_raw, group_scores, evidence_99, drivers, raw_signals, model_c_version, computed_at) FROM STDIN"
                ) as copy:
                    for idx in range(total_inferences):
                        sid = df["site_id"].iat[idx]
                        dt = dates_str[idx]
                        status = str(df["model_c_level"].iat[idx])
                        c_score = float(df["c_score"].iat[idx]) if pd.notna(df["c_score"].iat[idx]) else None
                        c_raw = float(df["c_raw"].iat[idx]) if pd.notna(df["c_raw"].iat[idx]) else None
                        ev99 = int(df["evidence_99"].iat[idx]) if pd.notna(df["evidence_99"].iat[idx]) else 0

                        grp = {
                            "intensity": float(df["intensity_raw_pct"].iat[idx]) if pd.notna(df["intensity_raw_pct"].iat[idx]) else None,
                            "density": float(df["density_raw_pct"].iat[idx]) if pd.notna(df["density_raw_pct"].iat[idx]) else None,
                            "recurrence": float(df["recurrence_raw_pct"].iat[idx]) if pd.notna(df["recurrence_raw_pct"].iat[idx]) else None,
                            "change": float(df["change_raw_pct"].iat[idx]) if pd.notna(df["change_raw_pct"].iat[idx]) else None,
                        }
                        drivers = [d.strip() for d in str(df["anomaly_drivers"].iat[idx]).split(",") if d.strip()] if pd.notna(df["anomaly_drivers"].iat[idx]) else []
                        raw = _model_c_raw_signals(df, idx)

                        copy.write_row((
                            sid, dt, status, c_score, c_raw,
                            json.dumps(grp), ev99, json.dumps(drivers), json.dumps(raw),
                            "2026-09-04-r1", now_iso
                        ))
            conn.commit()
        finally:
            conn.close()
    else:
        db = SessionLocal()
        try:
            records = []
            for idx in range(total_inferences):
                records.append({
                    "site_id": df["site_id"].iat[idx],
                    "acq_date": df["acq_date"].iat[idx].date(),
                    "model_c_status": str(df["model_c_level"].iat[idx]),
                    "c_score": float(df["c_score"].iat[idx]) if pd.notna(df["c_score"].iat[idx]) else None,
                    "c_raw": float(df["c_raw"].iat[idx]) if pd.notna(df["c_raw"].iat[idx]) else None,
                    "group_scores": _model_c_group_scores(df, idx),
                    "evidence_99": int(df["evidence_99"].iat[idx]) if pd.notna(df["evidence_99"].iat[idx]) else 0,
                    "drivers": _model_c_drivers(df, idx),
                    "raw_signals": _model_c_raw_signals(df, idx),
                    "model_c_version": "2026-09-04-r1",
                    "computed_at": datetime.now(timezone.utc)
                })
                if len(records) >= 5000:
                    db.bulk_insert_mappings(SiteDailyInference, records)
                    db.commit()
                    records = []
            if records:
                db.bulk_insert_mappings(SiteDailyInference, records)
                db.commit()
        finally:
            db.close()

    logger.info(f"Inserted {total_inferences} daily inferences in {time.time()-t0:.2f}s.")

    # 2. Materialize latest site_model_c
    t1 = time.time()
    logger.info("Materializing latest Model C status per site...")
    df_latest = df.sort_values("acq_date").drop_duplicates(subset=["site_id"], keep="last")
    total_latest = len(df_latest)
    latest_dates = df_latest["acq_date"].dt.strftime("%Y-%m-%d").tolist()

    if IS_POSTGRES:
        conn = get_raw_psycopg_conn()
        try:
            with conn.cursor() as cur:
                with cur.copy(
                    "COPY site_model_c (site_id, event_date, operational_status, c_score, c_raw, group_scores, evidence_99, drivers, history_counts, model_version, computed_at) FROM STDIN"
                ) as copy:
                    for idx in range(total_latest):
                        sid = df_latest["site_id"].iat[idx]
                        dt = latest_dates[idx]
                        status = str(df_latest["model_c_level"].iat[idx])
                        c_score = float(df_latest["c_score"].iat[idx]) if pd.notna(df_latest["c_score"].iat[idx]) else None
                        c_raw = float(df_latest["c_raw"].iat[idx]) if pd.notna(df_latest["c_raw"].iat[idx]) else None
                        ev99 = int(df_latest["evidence_99"].iat[idx]) if pd.notna(df_latest["evidence_99"].iat[idx]) else 0

                        grp = {
                            "intensity": float(df_latest["intensity_raw_pct"].iat[idx]) if pd.notna(df_latest["intensity_raw_pct"].iat[idx]) else None,
                            "density": float(df_latest["density_raw_pct"].iat[idx]) if pd.notna(df_latest["density_raw_pct"].iat[idx]) else None,
                            "recurrence": float(df_latest["recurrence_raw_pct"].iat[idx]) if pd.notna(df_latest["recurrence_raw_pct"].iat[idx]) else None,
                            "change": float(df_latest["change_raw_pct"].iat[idx]) if pd.notna(df_latest["change_raw_pct"].iat[idx]) else None,
                        }
                        drivers = [d.strip() for d in str(df_latest["anomaly_drivers"].iat[idx]).split(",") if d.strip()] if pd.notna(df_latest["anomaly_drivers"].iat[idx]) else []
                        hist = {
                            "history_active_days": int(df_latest["history_active_days"].iat[idx]) if pd.notna(df_latest["history_active_days"].iat[idx]) else 0,
                            "history_span_days": int(df_latest["history_span_days"].iat[idx]) if pd.notna(df_latest["history_span_days"].iat[idx]) else 0,
                        }

                        copy.write_row((
                            sid, dt, status, c_score, c_raw,
                            json.dumps(grp), ev99, json.dumps(drivers),
                            json.dumps(hist), "2026-09-04-r1", now_iso
                        ))
            conn.commit()
        finally:
            conn.close()
    else:
        db = SessionLocal()
        try:
            records = []
            for idx in range(total_latest):
                records.append({
                    "site_id": df_latest["site_id"].iat[idx],
                    "event_date": df_latest["acq_date"].iat[idx].date(),
                    "operational_status": str(df_latest["model_c_level"].iat[idx]),
                    "c_score": float(df_latest["c_score"].iat[idx]) if pd.notna(df_latest["c_score"].iat[idx]) else None,
                    "c_raw": float(df_latest["c_raw"].iat[idx]) if pd.notna(df_latest["c_raw"].iat[idx]) else None,
                    "group_scores": _model_c_group_scores(df_latest, idx),
                    "evidence_99": int(df_latest["evidence_99"].iat[idx]) if pd.notna(df_latest["evidence_99"].iat[idx]) else 0,
                    "drivers": _model_c_drivers(df_latest, idx),
                    "history_counts": {
                        "history_active_days": int(df_latest["history_active_days"].iat[idx]) if pd.notna(df_latest["history_active_days"].iat[idx]) else 0,
                        "history_span_days": int(df_latest["history_span_days"].iat[idx]) if pd.notna(df_latest["history_span_days"].iat[idx]) else 0,
                    },
                    "model_version": "2026-09-04-r1",
                    "computed_at": datetime.now(timezone.utc)
                })
                if len(records) >= 5000:
                    db.bulk_insert_mappings(SiteModelC, records)
                    db.commit()
                    records = []
            if records:
                db.bulk_insert_mappings(SiteModelC, records)
                db.commit()
        finally:
            db.close()

    logger.info(f"Materialized {total_latest} site_model_c records in {time.time()-t1:.2f}s.")
    return total_inferences, total_latest


def _model_c_group_scores(frame: pd.DataFrame, idx: int) -> dict:
    return {
        "intensity": _optional_float(frame["intensity_raw_pct"].iat[idx]),
        "density": _optional_float(frame["density_raw_pct"].iat[idx]),
        "recurrence_burst": _optional_float(frame["recurrence_raw_pct"].iat[idx]),
        "change": _optional_float(frame["change_raw_pct"].iat[idx]),
    }


def _model_c_raw_signals(frame: pd.DataFrame, idx: int) -> dict:
    return {
        "intensity_raw": _optional_float(frame["intensity_raw"].iat[idx]),
        "density_raw": _optional_float(frame["density_raw"].iat[idx]),
        "recurrence_raw": _optional_float(frame["recurrence_raw"].iat[idx]),
        "change_raw": _optional_float(frame["change_raw"].iat[idx]),
        "ewma_score": _optional_float(frame["ewma_score"].iat[idx]),
        "cusum_score": _optional_float(frame["cusum_score"].iat[idx]),
    }


def _model_c_drivers(frame: pd.DataFrame, idx: int) -> list:
    value = frame["anomaly_drivers"].iat[idx]
    return [item.strip() for item in str(value).split(",") if item.strip()] if pd.notna(value) else []


def clean_dict_for_json(d: dict) -> dict:
    """Recursively replaces NaN with None for valid JSON serialization."""
    clean = {}
    for k, v in d.items():
        if isinstance(v, float) and (np.isnan(v) or np.isinf(v)):
            clean[k] = None
        elif pd.isna(v):
            clean[k] = None
        elif isinstance(v, dict):
            clean[k] = clean_dict_for_json(v)
        else:
            clean[k] = v
    return clean


def bootstrap_facility_evidence(evidence_dir: str = "data/evidence"):
    """Load persistent facility evidence only (GEM and World Bank GFMR)."""
    logger.info(f"Bootstrapping external evidence datasets from {evidence_dir}...")
    records = []

    # 1. World Bank Flaring
    wb_file = os.path.join(evidence_dir, "worldbank_gfmr_india_2025.csv")
    if os.path.exists(wb_file):
        df_wb = pd.read_csv(wb_file)
        for idx, row in df_wb.iterrows():
            records.append({
                "evidence_id": f"GFMR_{idx:05d}",
                "source_name": "WORLDBANK_GFMR",
                "facility_name": _optional_string(row.get("facility_name")) or f"Flare_{idx}",
                "facility_type": _optional_string(row.get("subclass")) or "gas_flare",
                "latitude": float(row["latitude"]),
                "longitude": float(row["longitude"]),
                "coordinate_quality": _optional_string(row.get("coordinate_quality")) or "HIGH",
                "source_url": _optional_string(row.get("source_url")),
                "attributes": clean_dict_for_json(row.to_dict())
            })
        logger.info(f"Loaded {len(df_wb)} World Bank GFMR flaring records.")

    # 2. GEM Power Plants
    gem_file = os.path.join(evidence_dir, "gem_gipt_india.csv")
    if os.path.exists(gem_file):
        df_gem = pd.read_csv(gem_file, low_memory=False)
        for idx, row in df_gem.iterrows():
            records.append({
                "evidence_id": f"GEM_{idx:05d}",
                "source_name": "GEM_GIPT",
                "facility_name": _optional_string(row.get("facility_name")) or f"PowerPlant_{idx}",
                "facility_type": _optional_string(row.get("subclass")) or "power_plant",
                "latitude": float(row["latitude"]),
                "longitude": float(row["longitude"]),
                "coordinate_quality": _optional_string(row.get("coordinate_quality")) or "EXACT",
                "source_url": _optional_string(row.get("source_url")),
                "attributes": clean_dict_for_json(row.to_dict())
            })
        logger.info(f"Loaded {len(df_gem)} GEM GIPT power plant records.")

    if records:
        db = SessionLocal()
        try:
            total = len(records)
            for i in range(0, total, 5000):
                chunk = records[i:i + 5000]
                db.bulk_insert_mappings(FacilityEvidence, chunk)
                db.commit()
            logger.info(f"Successfully inserted {total} facility evidence records.")
        finally:
            db.close()

    return len(records)


def bootstrap_event_evidence(evidence_dir: str = "data/evidence"):
    """Load date-bound ICAR and FSI observations without treating them as facilities."""
    specs = (
        ("icar_creams_crop_burn_2025.csv", "ICAR_IARI_CREAMS", "crop_residue_burn", "ICAR"),
        ("fsi_forest_fire_2025.csv", "FSI_FOREST_FIRE", "forest_fire", "FSI"),
    )
    records = []
    retrieved_at = datetime.now(timezone.utc)
    for filename, source_name, default_type, prefix in specs:
        path = os.path.join(evidence_dir, filename)
        if not os.path.exists(path):
            continue
        frame = pd.read_csv(path, low_memory=False)
        for idx, row in frame.iterrows():
            event_date = pd.to_datetime(row.get("event_date"), errors="coerce")
            event_end = pd.to_datetime(row.get("event_end_date"), errors="coerce")
            acq_time = _optional_string(row.get("acq_time")) or "00:00:00"
            observed_at = None
            if pd.notna(event_date):
                parsed_time = pd.to_datetime(acq_time, errors="coerce")
                observed_at = event_date.to_pydatetime().replace(tzinfo=timezone.utc)
                if pd.notna(parsed_time):
                    observed_at = observed_at.replace(
                        hour=parsed_time.hour, minute=parsed_time.minute, second=parsed_time.second
                    )
            records.append({
                "evidence_id": f"{prefix}_{idx:06d}",
                "source_name": source_name,
                "evidence_type": _optional_string(row.get("subclass")) or default_type,
                "reference_id": _optional_string(row.get("reference_id")),
                "latitude": float(row["latitude"]),
                "longitude": float(row["longitude"]),
                "event_start": event_date.to_pydatetime().replace(tzinfo=timezone.utc) if pd.notna(event_date) else None,
                "event_end": event_end.to_pydatetime().replace(tzinfo=timezone.utc) if pd.notna(event_end) else None,
                "observed_at": observed_at,
                "retrieved_at": retrieved_at,
                "source_version": "2025-frozen",
                "coordinate_quality": "SATELLITE_DERIVED",
                "temporal_quality": "EVENT_DATE",
                "authority_level": "OFFICIAL_EXTERNAL_REFERENCE",
                "source_url": _optional_string(row.get("source_url")),
                "attributes": clean_dict_for_json(row.to_dict()),
            })
        logger.info("Loaded %d time-bound records from %s.", len(frame), filename)
    db = SessionLocal()
    try:
        for start in range(0, len(records), 5000):
            db.bulk_insert_mappings(EventEvidence, records[start:start + 5000])
            db.commit()
    finally:
        db.close()
    return len(records)


def bootstrap_model_versions():
    """Register the active stack with real content hashes."""
    logger.info("Registering model versions...")
    artifacts = {
        "A_CORE": "backend/models/MODEL_A_FINAL.joblib",
        "MODEL_B": "backend/config/model_b.json",
        "MODEL_C": "backend/models/MODEL_C_V3_FROZEN.joblib",
        "DECISION_ENGINE": "backend/config/decision_engine.json",
    }
    versions = []
    for component, path_string in artifacts.items():
        path = _repo_root / path_string
        if not path.is_file():
            raise FileNotFoundError(f"Required active-stack artifact is missing: {path_string}")
        versions.append({
            "component": component,
            "version": "2026-09-04-r1",
            "artifact_sha256": _sha256_file(path),
            "config": {"repo_path": path_string},
            "is_active": True,
        })

    db = SessionLocal()
    try:
        db.query(ModelVersion).update({ModelVersion.is_active: False})
        for v in versions:
            v["activated_at"] = datetime.now(timezone.utc)
            db.merge(ModelVersion(**v))
        db.commit()
        logger.info("Registered 4 active model stack components.")
    finally:
        db.close()


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def verify_packaging_gate() -> None:
    """Fail before schema/data mutation when the authoritative package is incomplete."""
    missing = [relative for relative in REQUIRED_FILES if not (PROJECT_ROOT / relative).is_file()]
    mismatches = _verify_declared_checksums()
    manifest_issue = None if missing else _active_manifest_issue()
    if missing or mismatches or manifest_issue:
        parts = []
        if missing:
            parts.append("missing: " + ", ".join(missing))
        if mismatches:
            parts.append("checksum mismatch: " + ", ".join(mismatches))
        if manifest_issue:
            parts.append(manifest_issue)
        raise RuntimeError("P0 packaging gate failed (" + "; ".join(parts) + ")")


def bootstrap_historical_stack_snapshot() -> str:
    """Record the common frozen 2025 cutoff without declaring it live-current."""
    snapshot_id = hashlib.sha256(b"2026-09-04-r1:2025-12-31:VIIRS_NOAA20_NRT").hexdigest()
    db = SessionLocal()
    try:
        row = db.query(StackSnapshot).filter_by(snapshot_id=snapshot_id).one_or_none()
        if row is None:
            row = StackSnapshot(snapshot_id=snapshot_id)
            db.add(row)
        row.model_stack_version = "2026-09-04-r1"
        row.data_through_date = date(2025, 12, 31)
        row.primary_firms_source = "VIIRS_NOAA20_NRT"
        row.a_core_artifact_sha256 = _sha256_file(_repo_root / "backend/models/MODEL_A_FINAL.joblib")
        row.c_artifact_sha256 = _sha256_file(_repo_root / "backend/models/MODEL_C_V3_FROZEN.joblib")
        row.feature_version = FEATURE_VERSION
        row.resolver_version = "incremental-member-radius-750m-min3-v1"
        row.backfill_completed_at = None
        row.status = "HISTORICAL"
        db.commit()
    finally:
        db.close()
    return snapshot_id


def bootstrap_alerts():
    """
    Generates operational alerts for current high-severity anomalies using DecisionEngine.
    Finds sites where Model C is ELEVATED, ANOMALOUS, or CRITICAL, or Model B is REACTIVATED.
    """
    t0 = time.time()
    logger.info("Evaluating initial operational alerts from DecisionEngine...")
    engine_inst = DecisionEngine()

    db = SessionLocal()
    try:
        results = (
            db.query(
                SiteModelC.site_id,
                SiteModelC.event_date,
                SiteModelC.operational_status,
                SiteModelA.decision.label("a_decision"),
                SiteModelA.core_probability.label("a_prob"),
                SiteModelB.state.label("b_state")
            )
            .join(SiteModelA, SiteModelC.site_id == SiteModelA.site_id)
            .join(SiteModelB, SiteModelC.site_id == SiteModelB.site_id)
            .filter(
                (SiteModelC.operational_status.in_(["CRITICAL", "ANOMALOUS", "ELEVATED"])) |
                (SiteModelB.state == "REACTIVATED")
            )
            .all()
        )

        logger.info(f"Evaluating {len(results)} candidate sites for alert generation...")
        alert_records = []
        seen_fps = set()
        for r in results:
            site_id, event_date, c_status, a_dec, a_prob, b_state = r
            dt_str = str(event_date) if event_date else "2025-12-31"

            eval_res = engine_inst.evaluate(
                site_id=site_id,
                site_day=dt_str,
                model_a_result={"decision": a_dec, "core_probability": a_prob},
                model_b_result={"state": b_state},
                model_c_result={"status": c_status}
            )

            if eval_res.get("alert_type") != "NO_ALERT":
                fp = eval_res.get("alert_fingerprint") or eval_res.get("fingerprint")
                if not fp or fp in seen_fps:
                    continue
                seen_fps.add(fp)

                alert_id = f"ALT_{site_id}_{dt_str}_{eval_res['alert_type']}"
                alert_day = event_date if event_date else datetime.strptime(dt_str, "%Y-%m-%d").date()
                alert_records.append({
                    "alert_id": alert_id,
                    "site_id": site_id,
                    "site_day": alert_day,
                    "alert_type": eval_res["alert_type"],
                    "alert_level": eval_res["alert_level"],
                    "headline": eval_res["headline"],
                    "reason_codes": eval_res.get("reason_codes", []),
                    "evidence_required": eval_res.get("evidence_required", False),
                    "fingerprint": fp,
                    "status": "ACTIVE",
                    "is_escalation": eval_res.get("is_escalation", False),
                    "created_at": datetime.now(timezone.utc),
                    "updated_at": datetime.now(timezone.utc)
                })

        for chunk_idx in range(0, len(alert_records), 1000):
            chunk = alert_records[chunk_idx:chunk_idx + 1000]
            db.bulk_insert_mappings(Alert, chunk)
            db.commit()

        logger.info(f"Generated and stored {len(alert_records)} operational alerts in {time.time()-t0:.2f}s.")
        return len(alert_records)
    finally:
        db.close()


def main():
    parser = argparse.ArgumentParser(description="Bootstrap SIH26162 Database")
    parser.add_argument("--clean", action="store_true", help="Truncate existing tables before loading")
    parser.add_argument("--limit", type=int, default=None, help="Limit number of records per table (for testing)")
    parser.add_argument("--skip-daily", action="store_true", help="Skip loading large daily activity dataset")
    parser.add_argument("--skip-inferences", action="store_true", help="Skip loading large daily inferences dataset")
    parser.add_argument("--evidence-only", action="store_true", help="Only load evidence, versions, and alerts")
    parser.add_argument("--init-only", action="store_true", help="Only create database schema without loading data")
    args = parser.parse_args()

    if not args.init_only and not args.evidence_only:
        verify_packaging_gate()
        validate_feature_builder_snapshot()

    print("=== SIH26162 Full Database Bootstrap ===")
    logger.info("Initializing database schema...")
    init_db()

    if args.init_only:
        logger.info("Schema initialized. Exiting as --init-only was specified.")
        return

    if args.clean:
        clean_database()

    t_start = time.time()

    if args.evidence_only:
        n_sites, n_detections, n_a, n_b, n_daily, n_inf, n_c = 0, 0, 0, 0, 0, 0, 0
    else:
        n_sites = bootstrap_source_sites("data/bootstrap/source_sites_ground_truth_FINAL.csv", limit=args.limit)
        hydrate_source_static_features("data/bootstrap/source_site_features_2025.parquet", limit=args.limit)
        n_detections = bootstrap_assigned_detections(
            "data/bootstrap/firms_detections_2025_assigned.parquet", limit=args.limit
        )
        n_a = bootstrap_model_a("data/bootstrap/source_site_features_2025.parquet", limit=args.limit)
        bootstrap_reference_labels("data/bootstrap/source_sites_ground_truth_FINAL.csv", limit=args.limit)
        n_b = bootstrap_model_b_states("data/bootstrap/MODEL_B_SOURCE_STATES_FINAL.csv", limit=args.limit)

        n_daily = 0
        if not args.skip_daily:
            n_daily = bootstrap_daily_activity("data/bootstrap/site_daily_activity.parquet", limit=args.limit)

        n_inf, n_c = 0, 0
        if not args.skip_inferences:
            n_inf, n_c = bootstrap_model_c_and_inferences("data/bootstrap/MODEL_C_EVENT_REPLAY_V3.parquet", limit=args.limit)

    n_ev = bootstrap_facility_evidence()
    n_event_ev = bootstrap_event_evidence()
    bootstrap_model_versions()
    n_alt = bootstrap_alerts()
    historical_snapshot_id = None
    if not args.evidence_only:
        historical_snapshot_id = bootstrap_historical_stack_snapshot()

    elapsed = time.time() - t_start
    print("\n" + "=" * 50)
    print("=== SIH26162 Database Bootstrap Complete ===")
    print(f"  Total Duration:         {elapsed:.1f} seconds")
    print(f"  Source Sites:           {n_sites:,}")
    print(f"  Assigned Detections:    {n_detections:,}")
    print(f"  Model A Baseline:       {n_a:,}")
    print(f"  Model B States:         {n_b:,}")
    print(f"  Site Daily Activity:    {n_daily:,}")
    print(f"  Site Daily Inferences:  {n_inf:,}")
    print(f"  Model C Materialized:   {n_c:,}")
    print(f"  Facility Evidence:      {n_ev:,}")
    print(f"  Event Evidence:         {n_event_ev:,}")
    print(f"  Operational Alerts:     {n_alt:,}")
    print(f"  Historical Snapshot:    {historical_snapshot_id or 'not created'}")
    print("=" * 50)


if __name__ == "__main__":
    main()
