"""
Bootstrap Database Ingestion Script
Populates PostgreSQL (using fast COPY) or SQLite with:
1. 79,365 frozen source sites
2. 79,365 Model A baseline predictions / decisions
3. 79,365 Model B precomputed states
4. 297,348 daily activity records (site_daily_activity.parquet)
5. 297,348 historical Model C event replay records (site_daily_inference)
6. 79,365 materialized latest Model C status records (site_model_c)
7. External facility evidence layers (GFMR, GEM, ICAR)
8. Model stack version metadata
9. Initial operational alerts generated by DecisionEngine
"""

import os
import sys
import json
import time
import logging
from pathlib import Path
from datetime import datetime, timezone
import argparse
import pandas as pd
import numpy as np

# Ensure project root is in sys.path
_repo_root = Path(__file__).resolve().parents[2]
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

from backend.app.db.session import engine, init_db, SessionLocal, DEFAULT_DATABASE_URL
from backend.app.db.models import (
    SourceSite,
    SiteDailyActivity,
    SiteModelA,
    SiteModelB,
    SiteModelC,
    SiteDailyInference,
    FacilityEvidence,
    ModelVersion,
    Alert
)
from backend.app.engines.decision_engine import DecisionEngine

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

IS_POSTGRES = DEFAULT_DATABASE_URL.startswith("postgresql")


def get_raw_psycopg_conn():
    """Returns a raw psycopg connection for fast COPY operations if PostgreSQL."""
    if not IS_POSTGRES:
        return None
    # Strip +psycopg dialect if present for direct psycopg connect
    conn_url = DEFAULT_DATABASE_URL.replace("postgresql+psycopg://", "postgresql://")
    import psycopg
    return psycopg.connect(conn_url, autocommit=False)


def clean_database():
    """Truncates all tables cleanly."""
    logger.info("Cleaning database tables...")
    if IS_POSTGRES:
        conn = get_raw_psycopg_conn()
        try:
            with conn.cursor() as cur:
                cur.execute("""
                    TRUNCATE TABLE 
                        alerts,
                        site_daily_inference,
                        site_model_c,
                        site_model_b,
                        site_model_a,
                        site_daily_activity,
                        firms_detections,
                        candidate_sources,
                        source_sites,
                        facility_evidence,
                        model_versions
                    CASCADE;
                """)
            conn.commit()
        finally:
            conn.close()
    else:
        db = SessionLocal()
        try:
            for model in [Alert, SiteDailyInference, SiteModelC, SiteModelB, SiteModelA,
                          SiteDailyActivity, FacilityEvidence, ModelVersion, SourceSite]:
                db.query(model).delete()
            db.commit()
        finally:
            db.close()
    logger.info("Tables truncated successfully.")


def bootstrap_source_sites(csv_path: str, limit: int = None):
    """Loads 79,365 physical source sites."""
    t0 = time.time()
    logger.info(f"Bootstrapping source sites from {csv_path}...")
    if not os.path.exists(csv_path):
        logger.warning(f"File not found: {csv_path}")
        return 0

    df = pd.read_csv(csv_path, low_memory=False)
    if limit:
        df = df.iloc[:limit]

    total = len(df)
    logger.info(f"Loaded CSV in {time.time()-t0:.2f}s ({total} rows). Preparing insert...")

    lc_cols = ["tree_fraction", "shrub_fraction", "grass_fraction", "crop_fraction",
               "built_fraction", "bare_fraction", "water_fraction", "wetland_fraction", "mangrove_fraction"]
    sp_cols = ["spatial_median_m", "spatial_p90_m", "spatial_std_m"]

    # Check which cols exist
    available_lc = [c for c in lc_cols if c in df.columns]
    available_sp = [c for c in sp_cols if c in df.columns]

    now_iso = datetime.now(timezone.utc).isoformat()

    if IS_POSTGRES:
        conn = get_raw_psycopg_conn()
        try:
            with conn.cursor() as cur:
                with cur.copy(
                    "COPY source_sites (site_id, latitude, longitude, status, land_cover, spatial_stats, created_at) FROM STDIN"
                ) as copy:
                    for idx in range(total):
                        sid = df["site_id"].iat[idx]
                        lat = float(df["latitude"].iat[idx])
                        lon = float(df["longitude"].iat[idx])

                        lc = {c: float(df[c].iat[idx]) for c in available_lc if pd.notna(df[c].iat[idx])} or None
                        sp = {c: float(df[c].iat[idx]) for c in available_sp if pd.notna(df[c].iat[idx])} or None

                        copy.write_row((
                            sid, lat, lon, "ACTIVE",
                            json.dumps(lc) if lc else None,
                            json.dumps(sp) if sp else None,
                            now_iso
                        ))
            conn.commit()
        finally:
            conn.close()
    else:
        db = SessionLocal()
        try:
            records = []
            for idx in range(total):
                sid = df["site_id"].iat[idx]
                lat = float(df["latitude"].iat[idx])
                lon = float(df["longitude"].iat[idx])
                lc = {c: float(df[c].iat[idx]) for c in available_lc if pd.notna(df[c].iat[idx])} or None
                sp = {c: float(df[c].iat[idx]) for c in available_sp if pd.notna(df[c].iat[idx])} or None
                records.append({
                    "site_id": sid, "latitude": lat, "longitude": lon, "status": "ACTIVE",
                    "land_cover": lc, "spatial_stats": sp, "created_at": datetime.now(timezone.utc)
                })
                if len(records) >= 5000:
                    db.bulk_insert_mappings(SourceSite, records)
                    db.commit()
                    records = []
            if records:
                db.bulk_insert_mappings(SourceSite, records)
                db.commit()
        finally:
            db.close()

    logger.info(f"Inserted {total} source sites in {time.time()-t0:.2f}s.")
    return total


def bootstrap_model_a(csv_path: str, limit: int = None):
    """Loads baseline Model A identity for all source sites."""
    t0 = time.time()
    logger.info(f"Bootstrapping Model A predictions from {csv_path}...")
    if not os.path.exists(csv_path):
        return 0

    df = pd.read_csv(csv_path, usecols=["site_id", "label_final"], low_memory=False)
    if limit:
        df = df.iloc[:limit]

    total = len(df)
    now_iso = datetime.now(timezone.utc).isoformat()

    if IS_POSTGRES:
        conn = get_raw_psycopg_conn()
        try:
            with conn.cursor() as cur:
                with cur.copy(
                    "COPY site_model_a (site_id, core_probability, class_name, decision, prithvi_status, model_version, computed_at) FROM STDIN"
                ) as copy:
                    for idx in range(total):
                        sid = df["site_id"].iat[idx]
                        lbl = str(df["label_final"].iat[idx]).upper()
                        if lbl == "INDUSTRIAL":
                            prob = 0.985
                            cls_name = "INDUSTRIAL"
                            dec = "INDUSTRIAL_CORE_STRONG"
                        elif lbl == "NONINDUSTRIAL":
                            prob = 0.120
                            cls_name = "NONINDUSTRIAL"
                            dec = "NONINDUSTRIAL"
                        elif lbl == "CONFLICT_REVIEW":
                            prob = 0.550
                            cls_name = "UNKNOWN"
                            dec = "UNKNOWN"
                        else:
                            prob = 0.450
                            cls_name = "UNKNOWN"
                            dec = "UNKNOWN"

                        copy.write_row((sid, prob, cls_name, dec, "NOT_TRIGGERED", "2026-09-04-r1", now_iso))
            conn.commit()
        finally:
            conn.close()
    else:
        db = SessionLocal()
        try:
            records = []
            for idx in range(total):
                sid = df["site_id"].iat[idx]
                lbl = str(df["label_final"].iat[idx]).upper()
                if lbl == "INDUSTRIAL":
                    prob, cls_name, dec = 0.985, "INDUSTRIAL", "INDUSTRIAL_CORE_STRONG"
                elif lbl == "NONINDUSTRIAL":
                    prob, cls_name, dec = 0.120, "NONINDUSTRIAL", "NONINDUSTRIAL"
                else:
                    prob, cls_name, dec = 0.450, "UNKNOWN", "UNKNOWN"

                records.append({
                    "site_id": sid, "core_probability": prob, "class_name": cls_name,
                    "decision": dec, "prithvi_status": "NOT_TRIGGERED",
                    "model_version": "2026-09-04-r1", "computed_at": datetime.now(timezone.utc)
                })
                if len(records) >= 5000:
                    db.bulk_insert_mappings(SiteModelA, records)
                    db.commit()
                    records = []
            if records:
                db.bulk_insert_mappings(SiteModelA, records)
                db.commit()
        finally:
            db.close()

    logger.info(f"Inserted {total} Model A states in {time.time()-t0:.2f}s.")
    return total


def bootstrap_model_b_states(csv_path: str, limit: int = None):
    """Loads 79,365 precomputed Model B states."""
    t0 = time.time()
    logger.info(f"Bootstrapping Model B states from {csv_path}...")
    if not os.path.exists(csv_path):
        return 0

    df = pd.read_csv(csv_path)
    if limit:
        df = df.iloc[:limit]

    total = len(df)
    now_iso = datetime.now(timezone.utc).isoformat()

    conf_col = "state_confidence" if "state_confidence" in df.columns else ("confidence" if "confidence" in df.columns else None)
    reason_col = "state_reason" if "state_reason" in df.columns else ("reason" if "reason" in df.columns else None)

    if IS_POSTGRES:
        conn = get_raw_psycopg_conn()
        try:
            with conn.cursor() as cur:
                with cur.copy(
                    "COPY site_model_b (site_id, state, confidence, reason, days_since_last, active_days_windows, model_version, computed_at) FROM STDIN"
                ) as copy:
                    for idx in range(total):
                        sid = df["site_id"].iat[idx]
                        state = df["model_b_state"].iat[idx]
                        conf = df[conf_col].iat[idx] if conf_col and pd.notna(df[conf_col].iat[idx]) else "HIGH"
                        reason = df[reason_col].iat[idx] if reason_col and pd.notna(df[reason_col].iat[idx]) else ""
                        dsl = int(df["days_since_last"].iat[idx]) if pd.notna(df["days_since_last"].iat[idx]) else None

                        windows = {
                            "active_days_30": int(df["active_days_30"].iat[idx]) if pd.notna(df.get("active_days_30", pd.Series([0])).iat[idx]) else 0,
                            "active_days_90": int(df["active_days_90"].iat[idx]) if pd.notna(df.get("active_days_90", pd.Series([0])).iat[idx]) else 0,
                            "active_days_180": int(df["active_days_180"].iat[idx]) if pd.notna(df.get("active_days_180", pd.Series([0])).iat[idx]) else 0,
                            "active_days_365": int(df["active_days_365"].iat[idx]) if pd.notna(df.get("active_days_365", pd.Series([0])).iat[idx]) else 0,
                        }

                        copy.write_row((sid, state, conf, reason, dsl, json.dumps(windows), "2026-09-04-r1", now_iso))
            conn.commit()
        finally:
            conn.close()
    else:
        db = SessionLocal()
        try:
            records = []
            for idx in range(total):
                sid = df["site_id"].iat[idx]
                state = df["model_b_state"].iat[idx]
                conf = df[conf_col].iat[idx] if conf_col and pd.notna(df[conf_col].iat[idx]) else "HIGH"
                reason = df[reason_col].iat[idx] if reason_col and pd.notna(df[reason_col].iat[idx]) else ""
                dsl = int(df["days_since_last"].iat[idx]) if pd.notna(df["days_since_last"].iat[idx]) else None
                windows = {
                    "active_days_30": int(df["active_days_30"].iat[idx]) if pd.notna(df.get("active_days_30", pd.Series([0])).iat[idx]) else 0,
                    "active_days_90": int(df["active_days_90"].iat[idx]) if pd.notna(df.get("active_days_90", pd.Series([0])).iat[idx]) else 0,
                    "active_days_180": int(df["active_days_180"].iat[idx]) if pd.notna(df.get("active_days_180", pd.Series([0])).iat[idx]) else 0,
                    "active_days_365": int(df["active_days_365"].iat[idx]) if pd.notna(df.get("active_days_365", pd.Series([0])).iat[idx]) else 0,
                }
                records.append({
                    "site_id": sid, "state": state, "confidence": conf, "reason": reason,
                    "days_since_last": dsl, "active_days_windows": windows,
                    "model_version": "2026-09-04-r1", "computed_at": datetime.now(timezone.utc)
                })
                if len(records) >= 5000:
                    db.bulk_insert_mappings(SiteModelB, records)
                    db.commit()
                    records = []
            if records:
                db.bulk_insert_mappings(SiteModelB, records)
                db.commit()
        finally:
            db.close()

    logger.info(f"Inserted {total} Model B states in {time.time()-t0:.2f}s.")
    return total


def bootstrap_daily_activity(parquet_path: str, limit: int = None):
    """Loads 297,348 daily activity records."""
    t0 = time.time()
    logger.info(f"Bootstrapping site daily activity from {parquet_path}...")
    if not os.path.exists(parquet_path):
        return 0

    df = pd.read_parquet(parquet_path)
    if limit:
        df = df.iloc[:limit]

    total = len(df)
    now_iso = datetime.now(timezone.utc).isoformat()
    dates_str = df["acq_date"].dt.strftime("%Y-%m-%d").tolist()

    if IS_POSTGRES:
        conn = get_raw_psycopg_conn()
        try:
            with conn.cursor() as cur:
                with cur.copy(
                    "COPY site_daily_activity (site_id, acq_date, detections, mean_frp, max_frp, updated_at) FROM STDIN"
                ) as copy:
                    for idx in range(total):
                        sid = df["site_id"].iat[idx]
                        dt = dates_str[idx]
                        det = int(df["detections"].iat[idx])
                        mean_frp = float(df["mean_frp"].iat[idx])
                        max_frp = float(df["max_frp"].iat[idx])
                        copy.write_row((sid, dt, det, mean_frp, max_frp, now_iso))
            conn.commit()
        finally:
            conn.close()
    else:
        db = SessionLocal()
        try:
            records = []
            for idx in range(total):
                records.append({
                    "site_id": df["site_id"].iat[idx],
                    "acq_date": df["acq_date"].iat[idx].date(),
                    "detections": int(df["detections"].iat[idx]),
                    "mean_frp": float(df["mean_frp"].iat[idx]),
                    "max_frp": float(df["max_frp"].iat[idx]),
                    "updated_at": datetime.now(timezone.utc)
                })
                if len(records) >= 5000:
                    db.bulk_insert_mappings(SiteDailyActivity, records)
                    db.commit()
                    records = []
            if records:
                db.bulk_insert_mappings(SiteDailyActivity, records)
                db.commit()
        finally:
            db.close()

    logger.info(f"Inserted {total} daily activity records in {time.time()-t0:.2f}s.")
    return total


def bootstrap_model_c_and_inferences(parquet_path: str, limit: int = None):
    """
    Loads:
    1. site_daily_inference (all 297,348 rows from MODEL_C_EVENT_REPLAY_V3.parquet)
    2. site_model_c (materialized latest Model C status for all 79,365 sites)
    """
    t0 = time.time()
    logger.info(f"Bootstrapping Model C inferences & materialized state from {parquet_path}...")
    if not os.path.exists(parquet_path):
        return 0, 0

    df = pd.read_parquet(parquet_path)
    if limit:
        df = df.iloc[:limit]

    total_inferences = len(df)
    now_iso = datetime.now(timezone.utc).isoformat()
    dates_str = df["acq_date"].dt.strftime("%Y-%m-%d").tolist()

    # 1. Insert site_daily_inference
    logger.info(f"Inserting {total_inferences} daily inferences...")
    if IS_POSTGRES:
        conn = get_raw_psycopg_conn()
        try:
            with conn.cursor() as cur:
                with cur.copy(
                    "COPY site_daily_inference (site_id, acq_date, model_c_status, c_score, c_raw, group_scores, evidence_99, drivers, model_c_version, computed_at) FROM STDIN"
                ) as copy:
                    for idx in range(total_inferences):
                        sid = df["site_id"].iat[idx]
                        dt = dates_str[idx]
                        status = str(df["model_c_level"].iat[idx])
                        c_score = float(df["c_score"].iat[idx]) if pd.notna(df["c_score"].iat[idx]) else None
                        c_raw = float(df["c_raw"].iat[idx]) if pd.notna(df["c_raw"].iat[idx]) else None
                        ev99 = int(df["evidence_99"].iat[idx]) if pd.notna(df["evidence_99"].iat[idx]) else 0

                        grp = {
                            "intensity": float(df["intensity_raw_pct"].iat[idx]) if pd.notna(df["intensity_raw_pct"].iat[idx]) else None,
                            "density": float(df["density_raw_pct"].iat[idx]) if pd.notna(df["density_raw_pct"].iat[idx]) else None,
                            "recurrence": float(df["recurrence_raw_pct"].iat[idx]) if pd.notna(df["recurrence_raw_pct"].iat[idx]) else None,
                            "change": float(df["change_raw_pct"].iat[idx]) if pd.notna(df["change_raw_pct"].iat[idx]) else None,
                        }
                        drivers = [d.strip() for d in str(df["anomaly_drivers"].iat[idx]).split(",") if d.strip()] if pd.notna(df["anomaly_drivers"].iat[idx]) else []

                        copy.write_row((
                            sid, dt, status, c_score, c_raw,
                            json.dumps(grp), ev99, json.dumps(drivers),
                            "2026-09-04-r1", now_iso
                        ))
            conn.commit()
        finally:
            conn.close()
    else:
        db = SessionLocal()
        try:
            records = []
            for idx in range(total_inferences):
                records.append({
                    "site_id": df["site_id"].iat[idx],
                    "acq_date": df["acq_date"].iat[idx].date(),
                    "model_c_status": str(df["model_c_level"].iat[idx]),
                    "c_score": float(df["c_score"].iat[idx]) if pd.notna(df["c_score"].iat[idx]) else None,
                    "c_raw": float(df["c_raw"].iat[idx]) if pd.notna(df["c_raw"].iat[idx]) else None,
                    "group_scores": None,
                    "evidence_99": int(df["evidence_99"].iat[idx]) if pd.notna(df["evidence_99"].iat[idx]) else 0,
                    "drivers": None,
                    "model_c_version": "2026-09-04-r1",
                    "computed_at": datetime.now(timezone.utc)
                })
                if len(records) >= 5000:
                    db.bulk_insert_mappings(SiteDailyInference, records)
                    db.commit()
                    records = []
            if records:
                db.bulk_insert_mappings(SiteDailyInference, records)
                db.commit()
        finally:
            db.close()

    logger.info(f"Inserted {total_inferences} daily inferences in {time.time()-t0:.2f}s.")

    # 2. Materialize latest site_model_c
    t1 = time.time()
    logger.info("Materializing latest Model C status per site...")
    df_latest = df.sort_values("acq_date").drop_duplicates(subset=["site_id"], keep="last")
    total_latest = len(df_latest)
    latest_dates = df_latest["acq_date"].dt.strftime("%Y-%m-%d").tolist()

    if IS_POSTGRES:
        conn = get_raw_psycopg_conn()
        try:
            with conn.cursor() as cur:
                with cur.copy(
                    "COPY site_model_c (site_id, event_date, operational_status, c_score, c_raw, group_scores, evidence_99, drivers, history_counts, model_version, computed_at) FROM STDIN"
                ) as copy:
                    for idx in range(total_latest):
                        sid = df_latest["site_id"].iat[idx]
                        dt = latest_dates[idx]
                        status = str(df_latest["model_c_level"].iat[idx])
                        c_score = float(df_latest["c_score"].iat[idx]) if pd.notna(df_latest["c_score"].iat[idx]) else None
                        c_raw = float(df_latest["c_raw"].iat[idx]) if pd.notna(df_latest["c_raw"].iat[idx]) else None
                        ev99 = int(df_latest["evidence_99"].iat[idx]) if pd.notna(df_latest["evidence_99"].iat[idx]) else 0

                        grp = {
                            "intensity": float(df_latest["intensity_raw_pct"].iat[idx]) if pd.notna(df_latest["intensity_raw_pct"].iat[idx]) else None,
                            "density": float(df_latest["density_raw_pct"].iat[idx]) if pd.notna(df_latest["density_raw_pct"].iat[idx]) else None,
                            "recurrence": float(df_latest["recurrence_raw_pct"].iat[idx]) if pd.notna(df_latest["recurrence_raw_pct"].iat[idx]) else None,
                            "change": float(df_latest["change_raw_pct"].iat[idx]) if pd.notna(df_latest["change_raw_pct"].iat[idx]) else None,
                        }
                        drivers = [d.strip() for d in str(df_latest["anomaly_drivers"].iat[idx]).split(",") if d.strip()] if pd.notna(df_latest["anomaly_drivers"].iat[idx]) else []
                        hist = {
                            "history_active_days": int(df_latest["history_active_days"].iat[idx]) if pd.notna(df_latest["history_active_days"].iat[idx]) else 0,
                            "history_span_days": int(df_latest["history_span_days"].iat[idx]) if pd.notna(df_latest["history_span_days"].iat[idx]) else 0,
                        }

                        copy.write_row((
                            sid, dt, status, c_score, c_raw,
                            json.dumps(grp), ev99, json.dumps(drivers),
                            json.dumps(hist), "2026-09-04-r1", now_iso
                        ))
            conn.commit()
        finally:
            conn.close()
    else:
        db = SessionLocal()
        try:
            records = []
            for idx in range(total_latest):
                records.append({
                    "site_id": df_latest["site_id"].iat[idx],
                    "event_date": df_latest["acq_date"].iat[idx].date(),
                    "operational_status": str(df_latest["model_c_level"].iat[idx]),
                    "c_score": float(df_latest["c_score"].iat[idx]) if pd.notna(df_latest["c_score"].iat[idx]) else None,
                    "c_raw": float(df_latest["c_raw"].iat[idx]) if pd.notna(df_latest["c_raw"].iat[idx]) else None,
                    "group_scores": None,
                    "evidence_99": int(df_latest["evidence_99"].iat[idx]) if pd.notna(df_latest["evidence_99"].iat[idx]) else 0,
                    "drivers": None,
                    "history_counts": None,
                    "model_version": "2026-09-04-r1",
                    "computed_at": datetime.now(timezone.utc)
                })
                if len(records) >= 5000:
                    db.bulk_insert_mappings(SiteModelC, records)
                    db.commit()
                    records = []
            if records:
                db.bulk_insert_mappings(SiteModelC, records)
                db.commit()
        finally:
            db.close()

    logger.info(f"Materialized {total_latest} site_model_c records in {time.time()-t1:.2f}s.")
    return total_inferences, total_latest


def clean_dict_for_json(d: dict) -> dict:
    """Recursively replaces NaN with None for valid JSON serialization."""
    clean = {}
    for k, v in d.items():
        if isinstance(v, float) and (np.isnan(v) or np.isinf(v)):
            clean[k] = None
        elif pd.isna(v):
            clean[k] = None
        elif isinstance(v, dict):
            clean[k] = clean_dict_for_json(v)
        else:
            clean[k] = v
    return clean


def bootstrap_facility_evidence(evidence_dir: str = "data/evidence"):
    """Loads GEM power plants, World Bank flaring, and ICAR crop burn data."""
    logger.info(f"Bootstrapping external evidence datasets from {evidence_dir}...")
    records = []

    # 1. World Bank Flaring
    wb_file = os.path.join(evidence_dir, "worldbank_gfmr_india_2025.csv")
    if os.path.exists(wb_file):
        df_wb = pd.read_csv(wb_file)
        for idx, row in df_wb.iterrows():
            records.append({
                "evidence_id": f"GFMR_{idx:05d}",
                "source_name": "WORLDBANK_GFMR",
                "facility_name": str(row.get("facility_name", f"Flare_{idx}")),
                "facility_type": str(row.get("subclass", "gas_flare")),
                "latitude": float(row["latitude"]),
                "longitude": float(row["longitude"]),
                "coordinate_quality": str(row.get("coordinate_quality", "HIGH")),
                "source_url": str(row.get("source_url", "")),
                "attributes": clean_dict_for_json(row.to_dict())
            })
        logger.info(f"Loaded {len(df_wb)} World Bank GFMR flaring records.")

    # 2. GEM Power Plants
    gem_file = os.path.join(evidence_dir, "gem_gipt_india.csv")
    if os.path.exists(gem_file):
        df_gem = pd.read_csv(gem_file, low_memory=False)
        for idx, row in df_gem.iterrows():
            records.append({
                "evidence_id": f"GEM_{idx:05d}",
                "source_name": "GEM_GIPT",
                "facility_name": str(row.get("facility_name", f"PowerPlant_{idx}")),
                "facility_type": str(row.get("subclass", "power_plant")),
                "latitude": float(row["latitude"]),
                "longitude": float(row["longitude"]),
                "coordinate_quality": str(row.get("coordinate_quality", "EXACT")),
                "source_url": str(row.get("source_url", "")),
                "attributes": clean_dict_for_json(row.to_dict())
            })
        logger.info(f"Loaded {len(df_gem)} GEM GIPT power plant records.")

    # 3. ICAR Crop Burn
    icar_file = os.path.join(evidence_dir, "icar_creams_crop_burn_2025.csv")
    if os.path.exists(icar_file):
        df_icar = pd.read_csv(icar_file, low_memory=False)
        for idx, row in df_icar.iterrows():
            records.append({
                "evidence_id": f"ICAR_{idx:06d}",
                "source_name": "ICAR_CROP",
                "facility_name": str(row.get("event_name", row.get("facility_name", f"Crop_Burn_{idx}"))),
                "facility_type": str(row.get("subclass", "crop_residue_burn")),
                "latitude": float(row["latitude"]),
                "longitude": float(row["longitude"]),
                "coordinate_quality": str(row.get("coordinate_quality", "SATELLITE")),
                "source_url": str(row.get("source_url", "")),
                "attributes": clean_dict_for_json(row.to_dict())
            })
        logger.info(f"Loaded {len(df_icar)} ICAR CREAMS crop burn records.")

    if records:
        db = SessionLocal()
        try:
            total = len(records)
            for i in range(0, total, 5000):
                chunk = records[i:i + 5000]
                db.bulk_insert_mappings(FacilityEvidence, chunk)
                db.commit()
            logger.info(f"Successfully inserted {total} facility evidence records.")
        finally:
            db.close()

    return len(records)


def bootstrap_model_versions():
    """Registers the current active frozen model stack in model_versions table."""
    logger.info("Registering model versions...")
    versions = [
        {"component": "A_CORE", "version": "2026-09-04-r1", "artifact_sha256": "verified", "is_active": True},
        {"component": "MODEL_B", "version": "2026-09-04-r1", "artifact_sha256": "deterministic_rules", "is_active": True},
        {"component": "MODEL_C", "version": "2026-09-04-r1", "artifact_sha256": "v3_calibration", "is_active": True},
        {"component": "DECISION_ENGINE", "version": "2026-09-04-r1", "artifact_sha256": "frozen_matrix", "is_active": True},
    ]

    db = SessionLocal()
    try:
        for v in versions:
            v["activated_at"] = datetime.now(timezone.utc)
            db.merge(ModelVersion(**v))
        db.commit()
        logger.info("Registered 4 active model stack components.")
    finally:
        db.close()


def bootstrap_alerts():
    """
    Generates operational alerts for current high-severity anomalies using DecisionEngine.
    Finds sites where Model C is ELEVATED, ANOMALOUS, or CRITICAL, or Model B is REACTIVATED.
    """
    t0 = time.time()
    logger.info("Evaluating initial operational alerts from DecisionEngine...")
    engine_inst = DecisionEngine()

    db = SessionLocal()
    try:
        results = (
            db.query(
                SiteModelC.site_id,
                SiteModelC.event_date,
                SiteModelC.operational_status,
                SiteModelA.decision.label("a_decision"),
                SiteModelA.core_probability.label("a_prob"),
                SiteModelB.state.label("b_state")
            )
            .join(SiteModelA, SiteModelC.site_id == SiteModelA.site_id)
            .join(SiteModelB, SiteModelC.site_id == SiteModelB.site_id)
            .filter(
                (SiteModelC.operational_status.in_(["CRITICAL", "ANOMALOUS", "ELEVATED"])) |
                (SiteModelB.state == "REACTIVATED")
            )
            .all()
        )

        logger.info(f"Evaluating {len(results)} candidate sites for alert generation...")
        alert_records = []
        seen_fps = set()
        for r in results:
            site_id, event_date, c_status, a_dec, a_prob, b_state = r
            dt_str = str(event_date) if event_date else "2025-12-31"

            eval_res = engine_inst.evaluate(
                site_id=site_id,
                site_day=dt_str,
                model_a_result={"decision": a_dec, "core_probability": a_prob},
                model_b_result={"state": b_state},
                model_c_result={"status": c_status}
            )

            if eval_res.get("alert_type") != "NO_ALERT":
                fp = eval_res.get("alert_fingerprint") or eval_res.get("fingerprint")
                if not fp or fp in seen_fps:
                    continue
                seen_fps.add(fp)

                alert_id = f"ALT_{site_id}_{dt_str}_{eval_res['alert_type']}"
                alert_day = event_date if event_date else datetime.strptime(dt_str, "%Y-%m-%d").date()
                alert_records.append({
                    "alert_id": alert_id,
                    "site_id": site_id,
                    "site_day": alert_day,
                    "alert_type": eval_res["alert_type"],
                    "alert_level": eval_res["alert_level"],
                    "headline": eval_res["headline"],
                    "reason_codes": eval_res.get("reason_codes", []),
                    "evidence_required": eval_res.get("evidence_required", False),
                    "fingerprint": fp,
                    "status": "ACTIVE",
                    "is_escalation": eval_res.get("is_escalation", False),
                    "created_at": datetime.now(timezone.utc),
                    "updated_at": datetime.now(timezone.utc)
                })

        for chunk_idx in range(0, len(alert_records), 1000):
            chunk = alert_records[chunk_idx:chunk_idx + 1000]
            db.bulk_insert_mappings(Alert, chunk)
            db.commit()

        logger.info(f"Generated and stored {len(alert_records)} operational alerts in {time.time()-t0:.2f}s.")
        return len(alert_records)
    finally:
        db.close()


def main():
    parser = argparse.ArgumentParser(description="Bootstrap SIH26162 Database")
    parser.add_argument("--clean", action="store_true", help="Truncate existing tables before loading")
    parser.add_argument("--limit", type=int, default=None, help="Limit number of records per table (for testing)")
    parser.add_argument("--skip-daily", action="store_true", help="Skip loading large daily activity dataset")
    parser.add_argument("--skip-inferences", action="store_true", help="Skip loading large daily inferences dataset")
    parser.add_argument("--evidence-only", action="store_true", help="Only load evidence, versions, and alerts")
    parser.add_argument("--init-only", action="store_true", help="Only create database schema without loading data")
    args = parser.parse_args()

    print("=== SIH26162 Full Database Bootstrap ===")
    logger.info("Initializing database schema...")
    init_db()

    if args.init_only:
        logger.info("Schema initialized. Exiting as --init-only was specified.")
        return

    if args.clean:
        clean_database()

    t_start = time.time()

    if args.evidence_only:
        n_sites, n_a, n_b, n_daily, n_inf, n_c = 0, 0, 0, 0, 0, 0
    else:
        n_sites = bootstrap_source_sites("data/bootstrap/source_sites_ground_truth_FINAL.csv", limit=args.limit)
        n_a = bootstrap_model_a("data/bootstrap/source_sites_ground_truth_FINAL.csv", limit=args.limit)
        n_b = bootstrap_model_b_states("data/bootstrap/MODEL_B_SOURCE_STATES_FINAL.csv", limit=args.limit)

        n_daily = 0
        if not args.skip_daily:
            n_daily = bootstrap_daily_activity("data/bootstrap/site_daily_activity.parquet", limit=args.limit)

        n_inf, n_c = 0, 0
        if not args.skip_inferences:
            n_inf, n_c = bootstrap_model_c_and_inferences("data/bootstrap/MODEL_C_EVENT_REPLAY_V3.parquet", limit=args.limit)

    n_ev = bootstrap_facility_evidence()
    bootstrap_model_versions()
    n_alt = bootstrap_alerts()

    elapsed = time.time() - t_start
    print("\n" + "=" * 50)
    print("=== SIH26162 Database Bootstrap Complete ===")
    print(f"  Total Duration:         {elapsed:.1f} seconds")
    print(f"  Source Sites:           {n_sites:,}")
    print(f"  Model A Baseline:       {n_a:,}")
    print(f"  Model B States:         {n_b:,}")
    print(f"  Site Daily Activity:    {n_daily:,}")
    print(f"  Site Daily Inferences:  {n_inf:,}")
    print(f"  Model C Materialized:   {n_c:,}")
    print(f"  Facility Evidence:      {n_ev:,}")
    print(f"  Operational Alerts:     {n_alt:,}")
    print("=" * 50)


if __name__ == "__main__":
    main()
